---
# https://docs.fluxcd.io/projects/helm-operator/en/latest/references/helmrelease-custom-resource/
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rasa-x
  namespace: flux-test
  annotations:
spec:
  releaseName: rasa-x
  reuseValues: false
  wait: true
  chart:
    repository: https://rasahq.github.io/rasa-x-helm
    name: rasa-x
    version: 1.2.7
  values:
    rasax:
      tag: "0.27.5"
    rasa:
      tag: "1.9.5"
